package com.example.freelacetelegrambot.enums;

public enum InlineKeyButton {
    EDIT, CLOSE, DELETE, DONE, REJECTION, SHOW_COMMENT, EDIT_MAIL, EDIT_PHONE_NUMBER,
    ADD_LIKE_CATEGORY, RESEND_MAIL, GO_BACK_SETTING, CREATE_COMMENT, SELECT_EXECUTOR,
    RESPOND, SEND_MESSAGE, GO_BACK_SELECT_CATEGORIES

}
