package com.example.freelacetelegrambot.enums;

public enum InlineKeyButton {
    EDIT, CLOSE, DELETE, DONE, MESSAGE_CUSTOMER, MESSAGE_EXECUTOR,
    REJECTION, SEND_MESSAGE_EXECUTOR, SHOW_COMMENT, EDIT_MAIL, EDIT_PHONE_NUMBER, ADD_LIKE_CATEGORY, RESEND_MAIL, GO_BACK_SETTING, RESPOND

}
