package com.example.freelacetelegrambot.enums;

public enum State {
    NOT_ACTIVE_ACCOUNT,
    BASIK,
    REGISTRATION_EMAIL,
    REGISTRATION_PHONE_NUMBER,
    CREATE_TASK_NAME,
    CREATE_TASK_DESCRIPTION,
    CREATE_TASK_ADDRESS,
    CREATE_TASK_PRICE,
    CRATE_TASK_CATEGORY,
    CREATE_TASK_CATEGORY_COURIER

}
